/* QPT Workbench — data layer
 * Content condensed from "Quaternion Process Theory — Consolidated 2.x Specification, Edition 2.7".
 * All section references (§) point into that document.
 */
"use strict";

const QPT_DATA = {

  meta: {
    title: "Quaternion Process Theory",
    edition: "Consolidated 2.7",
    tagline: "Directed autopoietic navigation — one gate-passage at a time",
    gate: "𝒢 ≡ R ⊓ G",
    score: "S = ρ − δ − γ·ln k",
  },

  /* ---------------------------------------------------------------- boards */

  boards: [
    {
      id: "protocol",
      title: "The Generative Protocol",
      ref: "§14 · Part IV — The Quality Gate",
      note: "Every generative process, at every scale and recursion depth, runs this loop. " +
            "Commitment horizon = 1 (A13): the option space after the next gate passage does not yet exist.",
      columns: [
        { id: "initiation",  glyph: "(○)", cat: "first",  name: "Initiation",       step: "Step 1",
          desc: "Remove interference; let the system's coherence recruit attention to its weakest point. Record the locus indexically (“here”), not symbolically.",
          axioms: ["A11"] },
        { id: "encounter",   glyph: "[□]", cat: "second", name: "Encounter",        step: "Step 2",
          desc: "Engage actual causal operations at the recruited point. Raw observational records; contact duration matched to scale.",
          axioms: ["A2"] },
        { id: "gate",        glyph: "𝒢",   cat: "gate",   name: "Gate Evaluation",  step: "Step 3",
          desc: "Apply R ⊓ G — equivalently, test S ≥ θ. Proceed only on dual passage; otherwise diagnose via the five-layer model and return.",
          axioms: ["A9", "A10", "A15"] },
        { id: "articulation",glyph: "{△}", cat: "third",  name: "Articulation",     step: "Step 4",
          desc: "Name strictly downstream of passage. Test whether the name is recruited ({△}(○)) and operative ({△}[□]) — not merely organizational ({△}{△}).",
          axioms: ["A14"] },
        { id: "closure",     glyph: "↻",   cat: "cycle",  name: "Recursive Closure", step: "Step 5",
          desc: "Re-evaluate the enlarged whole. State, R-topology and boundaries have shifted; return to Step 1 at whatever scale now recruits.",
          axioms: ["A12", "A13"] },
      ],
      cards: [
        { id: "p1", column: "encounter",
          title: "“Here”: the onboarding drop-off",
          sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          source: "recruited", target: "grounded",
          rho: 0.95, delta: 0.07, gamma: 0.20, k: 3, theta: 0.50,
          scale: "meso", cycle: 0, axioms: ["A9", "A11"],
          note: "Locus recorded indexically (“here”), not symbolically. Attention was captured, not scanned — the weakest coherence point announced itself once interference was removed." },
        { id: "p2", column: "gate",
          title: "Q3 dashboard redesign (executive template)",
          sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          source: "initiated", target: "terminated",
          rho: 0.35, delta: 0.42, gamma: 0.30, k: 6, theta: 0.50,
          scale: "meso", cycle: 0, pathology: "content", death: "imposition",
          axioms: ["A10", "A13"],
          note: "Spec arrived before any encounter — a {△}→{△} trajectory. “Was this ever recruited?” No (○) trace: imposition, the most resistant death mode. Strengthen the living side before removal." },
        { id: "p3", column: "gate",
          title: "Felt wrongness in the query planner",
          sign: "⟨⦿○ ≈ ⊣○⟩", signName: "Qualisign–Icon–Rheme",
          source: "recruited", target: "terminated",
          rho: 0.88, delta: 0.35, gamma: 0.25, k: 5, theta: 0.50,
          scale: "micro", cycle: 0, pathology: "attentional", death: null,
          axioms: ["A9", "A10"],
          note: "Strong pull, no causal landing yet. Beautiful delusion: feels alive, ungrounded. Needs [□]-contact — a profile, a trace, a failing query — before any naming." },
        { id: "p4", column: "articulation",
          title: "Legacy schema migration",
          sign: "⟨⦿△ ≡ ⊣□⟩", signName: "Legisign–Symbol–Dicisign",
          source: "initiated", target: "grounded",
          rho: 0.60, delta: 0.10, gamma: 0.20, k: 2, theta: 0.30,
          scale: "macro", cycle: 1, pathology: "temporal", death: null,
          axioms: ["A10"],
          note: "Competent-dead: grounded, executed, unrecruited. Premature closure — the migration spec froze a partial contact; the name closed instead of opening further encounter." },
        { id: "p5", column: "articulation",
          title: "Rename `session` → `encounter`",
          sign: "⟨⦿△ ≡ ⊣α⟩", signName: "Legisign–Symbol–Abduction",
          source: "recruited", target: "grounded",
          rho: 0.90, delta: 0.05, gamma: 0.20, k: 2, theta: 0.45,
          scale: "meso", cycle: 1, pathology: null, death: null,
          axioms: ["A14"],
          note: "Living name: arrived through contact ({△}(○)), and it is operative ({△}[□]) — it opens new diagnostics: every “session” now asks what actually happened in the encounter." },
        { id: "p6", column: "initiation",
          title: "Deprecated auth middleware",
          sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          source: "initiated", target: "terminated",
          rho: 0.30, delta: 0.38, gamma: 0.30, k: 4, theta: 0.45,
          scale: "macro", cycle: 2, pathology: "structural", death: "fossil",
          axioms: ["A12"],
          note: "Fossil: “Was this once alive?” — yes; trace of generative origin persists. Diagnose through contact, strengthen the living side first, then minimum dissolution: remove one constraint, wait, sense reorganization." },
        { id: "p7", column: "encounter",
          title: "Button haptics at the coherence boundary",
          sign: "⟨⦿○ ≈ ⊣○⟩", signName: "Qualisign–Icon–Rheme",
          source: "recruited", target: "grounded",
          rho: 0.70, delta: 0.12, gamma: 0.25, k: 2, theta: 0.40,
          scale: "micro", cycle: 0, pathology: null, death: null,
          axioms: ["A15"],
          note: "Micro scale: haptic contact, seconds of duration. S ≈ θ — Zone 2, the phase transition; P(anchored) ≈ 0.5 and unstable. Stay with the encounter; do not plan past it." },
        { id: "p8", column: "gate",
          title: "Incident review that nobody feels",
          sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          source: "initiated", target: "terminated",
          rho: 0.40, delta: 0.50, gamma: 0.30, k: 8, theta: 0.40,
          scale: "macro", cycle: 1, pathology: "scalar", death: "residue",
          axioms: ["ML", "A11"],
          note: "Consequences route to dashboards rather than experiencing selves (⤓ₑ, dashboard substitution). The collective gate needs independent indexical capture — “here” landing on the same locus without prior communication." },
        { id: "p9", column: "closure",
          title: "Weekly “what recruited us?” review",
          sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          source: "recruited", target: "grounded",
          rho: 0.85, delta: 0.10, gamma: 0.20, k: 3, theta: 0.40,
          scale: "meso", cycle: 2, pathology: null, death: null,
          axioms: ["A12", "A13"],
          note: "Re-sensing the enlarged whole: the weakest point has moved, and edges at layer N+1 were created by resolution at N. The graph produced itself through its own operation." },
      ],
    },

    {
      id: "dialectic",
      title: "The Scheduled Dialectic",
      ref: "§19 · Part V — Coordination Physics",
      note: "Contentiousness follows the schedule χ: 0.9 →|π 0.7 →|π 0.5 →|π 0.3. Each phase is a DCGC stage; " +
            "the moderator (⟹ᵐⁿᵃᵛ¹ ⊗ |ᵍ ⊗ ⟹ᵐᵉᵐ) gates before integration and detects HALT.",
      columns: [
        { id: "explore",     glyph: "⟹ᵃᵇᵈ", cat: "first",  name: "Explore",     step: "χ = 0.9",
          desc: "Abductive navigation: hypothesis generation by ⟨⦿○ ≈ ⊣○⟩. Selected when S < θ₁.",
          axioms: ["A20"] },
        { id: "integrate",   glyph: "⟹ⁱⁿᵈ", cat: "second", name: "Integrate",   step: "χ = 0.7",
          desc: "Inductive navigation: evidence integration by ⟨⦿□ ⇢ ⊣□⟩. Selected when θ₁ ≤ S < θ₂.",
          axioms: ["A19", "A16"] },
        { id: "consolidate", glyph: "⟹ᵈᵉᵈ", cat: "third",  name: "Consolidate", step: "χ = 0.5",
          desc: "Deductive navigation: rule application by ⟨⦿△ ≡ ⊣△⟩. Selected when S ≥ θ₂. Thresholds tighten: τ⁽ᵗ⁺¹⁾ = min(τ⁽ᵗ⁾ + η·π⁽ᵗ⁾, τ_max).",
          axioms: ["A15", "A16"] },
        { id: "synthesize",  glyph: "⋗",    cat: "gate",   name: "Synthesize",  step: "χ = 0.3",
          desc: "Genesis: [□]⎕₁ ⋈ᵈ [□]⎕₂ under adequate mediation gives rise to [□]⎕ₑw — with at least one property present in no parent (A7).",
          axioms: ["A7", "A17"] },
      ],
      cards: [
        { id: "d1", column: "explore", kind: "position", agent: "u₁",
          title: "“Cache everything at the edge, always.”",
          sign: "⟨⦿△ ≡ ⊣α⟩", signName: "Legisign–Symbol–Abduction",
          reliability: 0.81, cycle: 0, axioms: ["A20"],
          note: "Hypothesis generated by resemblance to a past win. High contentiousness χ = 0.9: the position resists yielding until incoming arguments anchor (χ⁽ᵗ⁺¹⁾ = χ⁽ᵗ⁾·(1 − β·S_incoming))." },
        { id: "d2", column: "explore", kind: "position", agent: "u₂",
          title: "“Invalidate on every write — freshness first.”",
          sign: "⟨⦿△ ≡ ⊣α⟩", signName: "Legisign–Symbol–Abduction",
          reliability: 0.62, cycle: 0, axioms: ["A19"],
          note: "Dialectical pole of u₁: [□]⎕₁ ⋈ᵈ [□]⎕₂. Lower track record → lower normalized weight w = (Γ + ε₀) / Σᵥ(Γᵥ + ε₀)." },
        { id: "d3", column: "integrate", kind: "position", agent: "u₃",
          title: "p99 latency traces from the last three incidents",
          sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          reliability: 0.74, cycle: 0, axioms: ["A19"],
          note: "Evidence integration: the index points at what actually happened. ↑σ_support (ρ) and ↓σ_disagreement (Jensen–Shannon divergence) are tracked on Σᶜᵒⁿᵛ." },
        { id: "d4", column: "integrate", kind: "note",
          title: "Moderator: plateau π flagged on σ_disagreement",
          sign: "⟹ᵐⁿᵃᵛ¹ ⊗ |ᵍ ⊗ ⟹ᵐᵉᵐ", signName: "meta-navigator",
          reliability: null, cycle: 0, axioms: ["A16", "A17"],
          note: "Relative progress r⁽ᵗ⁾σ < ε_rel persisted for t_persist rounds → πσ. The moderator schedules the phase transition →|π and tightens τ toward convergence." },
        { id: "d5", column: "consolidate", kind: "position", agent: "u₄",
          title: "⋗ᵉ Tiered TTL, tuned by incident memory",
          sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          reliability: 0.77, cycle: 1, axioms: ["A7"],
          genesis: "incident-driven TTL tuning",
          note: "Emergent genesis (⋗ᵉ): incident-driven tuning is a property present in neither parent — not “cache everything”, not “invalidate always”. Mediation adequacy was sufficient; tension duration and intensity crossed threshold." },
        { id: "d6", column: "synthesize", kind: "note",
          title: "HALT probe",
          sign: "π_persist ∧ S ≥ θ ∧ quality_sufficient", signName: "termination condition",
          reliability: null, cycle: 1, axioms: ["A17"],
          note: "HALT ⟺ plateau persists while the gate passes and quality is sufficient. Bounded expectation: E[t_halt] = O(1/ε) for gated averaging; O(log 1/ε) under contraction." },
      ],
    },

    {
      id: "resolution",
      title: "The Resolution Procedure",
      ref: "§29 · Part VII — The Unified Field of Failure",
      note: "A phased procedure that is itself gaming-resistant: someone must experience whether it worked, " +
            "not merely measure completion. Alignment ∝ experiential_return (ML).",
      columns: [
        { id: "phase0", glyph: "0", cat: "first",  name: "Pre-diagnostic",       step: "Phase 0",
          desc: "Stakes, meta-rationality (solve / change-game / exit / refuse / wait / restore-experience), preference archaeology, experiential mapping: who experiences each level — where are the dead zones?",
          axioms: ["ML"] },
        { id: "phase1", glyph: "1", cat: "second", name: "Diagnostic mapping",   step: "Phase 1",
          desc: "Purpose excavation (stated / revealed / structural / latent / experienced), metric archaeology, gaming census to recursion depth ≥ 3, friction inventory.",
          axioms: ["L2", "L3"] },
        { id: "phase2", glyph: "2", cat: "third",  name: "Solution-space mapping", step: "Phase 2",
          desc: "Eliminate failed strategies; enumerate structural interventions; assess the experiential return of each.",
          axioms: ["ML"] },
        { id: "phase3", glyph: "3", cat: "third",  name: "Structural redesign",  step: "Phase 3",
          desc: "Multi-scale alignment, antifragile response, verification integration, exit options, governance, experiential return by design.",
          axioms: ["L4", "ML"] },
        { id: "phase4", glyph: "4", cat: "second", name: "Implementation",       step: "Phase 4",
          desc: "Gall's Law: simplest, smallest, most reversible first. Chesterton's Fence: understand what experience a structure encodes before removing it. Adversarial testing.",
          axioms: ["L5", "L6"] },
        { id: "phase5", glyph: "5", cat: "cycle",  name: "Evolutionary iteration", step: "Phase 5",
          desc: "Adapt on triggers; define exit conditions; guard the method against checkbox-completion and experiential theatre.",
          axioms: ["ML", "A14"] },
      ],
      cards: [
        { id: "r1", column: "phase0", tags: ["⤓ₑ", "dead-zone hunt"],
          title: "Experiential map: who actually feels deploy pain?",
          sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          cycle: 0, axioms: ["ML"],
          note: "Map every level of the system to its experiencer. The dead zones — consequences that land on no one — are where feedback-without-interiority takes root." },
        { id: "r2", column: "phase1", tags: ["PMG", "metric archaeology"],
          title: "Purpose excavation: the 99.9% uptime KPI",
          sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          cycle: 0, axioms: ["L2"],
          note: "Stated purpose: reliability. Revealed purpose: green dashboards. PMG = 1 − correlation(metric, purpose_outcomes) is the space into which optimization pressure leaks. Purpose debt D(t) = ∫ PMG du has been accruing for years." },
        { id: "r3", column: "phase1", tags: ["∇H", "⟨⟨⟩⟩"],
          title: "Gaming census ≥ depth 3: the review leaderboard",
          sign: "⟨⦿△ ≡ ⊣□⟩", signName: "Legisign–Symbol–Dicisign",
          cycle: 0, axioms: ["L2", "L3"],
          note: "Depth 1: rubber-stamp approvals. Depth 2: splitting PRs to farm count. Depth 3: the anti-gaming linter is now itself optimized (meta-hacking recursion ⟨⟨⟩⟩). Gaming lives in the null space of the representation." },
        { id: "r4", column: "phase3", tags: ["experiential return", "ML"],
          title: "On-call feels the alert they wrote",
          sign: "⟨⦿○ ≈ ⊣○⟩", signName: "Qualisign–Icon–Rheme",
          cycle: 1, axioms: ["ML"],
          note: "Shorten the loop action → consequence → experience → identity → action. A system stays aligned only as long as action reshapes the actor: alignment ∝ experiential_return." },
        { id: "r5", column: "phase4", tags: ["Chesterton's Fence"],
          title: "The Thursday deploy freeze",
          sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          cycle: 1, axioms: ["L5"],
          note: "Before removing the freeze, understand what experience it encodes: it is the fossil of a catastrophic Thursday incident — load-bearing friction, not vestigial. Removal leaves a void with no latent structure to fill it." },
        { id: "r6", column: "phase5", tags: ["exit condition"],
          title: "Alert noise below the felt threshold",
          sign: "⟨⦿△ ≡ ⊣α⟩", signName: "Legisign–Symbol–Abduction",
          cycle: 1, axioms: ["ML", "A14"],
          note: "Exit when the on-call's experienced noise — not the dashboard's — falls below threshold. Guard against experiential theatre: a retro where nobody's identity is at stake is {△} ritual, not (○) contact." },
      ],
    },
  ],

  /* ------------------------------------------------------------- reference */

  reference: {

    formulas: [
      { id: "f-gate",   name: "Quality Gate",            body: "𝒢 ≡ R ⊓ G",                               ref: "§7" },
      { id: "f-score",  name: "Anchoring score",         body: "S = ρ − δ − γ·log k  ;  pass iff S ≥ θ",  ref: "§8" },
      { id: "f-sigmoid",name: "Sigmoid link",            body: "P(anchored | S) = 1 / (1 + e^(−a(S − θ)))", ref: "§8.1" },
      { id: "f-conv",   name: "Convergence",             body: "CONVERGED ⟺ ∇Σᶜᵒⁿᵛ ≈ 0",                  ref: "§17" },
      { id: "f-tau",    name: "Adaptive tightening",     body: "τ⁽ᵗ⁺¹⁾ = min(τ⁽ᵗ⁾ + η·π⁽ᵗ⁾, τ_max)",      ref: "§18" },
      { id: "f-halt",   name: "Termination",             body: "HALT ⟺ π_persist ∧ S ≥ θ ∧ quality_sufficient", ref: "§18" },
      { id: "f-chi",    name: "Yield schedule",          body: "χ⁽ᵗ⁺¹⁾ᵤ = χ⁽ᵗ⁾ᵤ · (1 − β·S_incoming)",    ref: "§19" },
      { id: "f-verif",  name: "Verification cost",       body: "V(x) = V_compute + V_judgment ;  lim_(AI→∞) V = V_judgment", ref: "§21" },
      { id: "f-trust",  name: "Decomposed trust",        body: "T = min(T_kinetic, T_potential) · T_grounding", ref: "§23" },
      { id: "f-align",  name: "Promise-binding alignment", body: "α(A,P) = |b_A ∩ b_P| / |b_P|  ;  α_chain ≤ min_i α_i", ref: "§24" },
      { id: "f-debt",   name: "Purpose debt",            body: "D(t) = ∫₀ᵗ PMG(u) du",                    ref: "§26" },
      { id: "f-metal",  name: "Meta-Law",                body: "alignment ∝ experiential_return",         ref: "§27" },
    ],

    axioms: [
      { id: "A1",  name: "Completeness",         body: "∀P : P ≈ (○) ⊗ [□] ⊗ {△}", part: "I" },
      { id: "A2",  name: "Irreducibility",       body: "(○) ≢ [□] ≢ {△}", part: "I" },
      { id: "A3",  name: "Dependency / Prescission", body: "{△} ⊃ [□] ⊃ (○)  ⟺  (○) ⊢ [□] ⊢ {△} — you cannot build downward", part: "I" },
      { id: "A4",  name: "Preservation",         body: "[□]⎕(X → Y) = [□]⎕", part: "III" },
      { id: "A5",  name: "Composition",          body: "[□]⎕₁₊₂ = [□]⎕₁ ∘ [□]⎕₂", part: "III" },
      { id: "A6",  name: "Cycle coherence",      body: "(○) → [□] → {△} → (○) preserves continuity", part: "III" },
      { id: "A7",  name: "Genesis emergence",    body: "∃ property([□]⎕ₑw) ∉ parents", part: "III" },
      { id: "A8",  name: "Unlimited semiosis",   body: "interpretant_n = sign_(n+1) — meaning is never closed", part: "II" },
      { id: "A9",  name: "Dual gate",            body: "living ⟺ (R ⊓ G)   [quantitatively S ≥ θ]", part: "IV" },
      { id: "A10", name: "Trajectory",           body: "the gate scores (source, target), not content", part: "IV" },
      { id: "A11", name: "Non-outsourceability", body: "R is (○) → [□] capture; scoring/aggregation is {△} → {△} and cannot substitute", part: "IV" },
      { id: "A12", name: "Non-transitivity",     body: "the developmental graph is autopoietic; edges at N+1 are created by resolution at N", part: "IV" },
      { id: "A13", name: "Commitment horizon",   body: "living process ⟺ horizon = 1", part: "IV" },
      { id: "A14", name: "Self-modification",    body: "the gate applies to QPT's own {△}: living names strengthened, dead dissolved (μ_self)", part: "IV" },
      { id: "A15", name: "Phase transition",     body: "S ≥ θ ⟺ anchored regime", part: "V" },
      { id: "A16", name: "Monotone descent",     body: "⟹⎕|ᵍ ⊩ D_descent⁽ᵗ⁺¹⁾ ≤ D_descent⁽ᵗ⁾", part: "V" },
      { id: "A17", name: "Bounded termination",  body: "⟹⎕|ᵍ_avg ⊩ E[t_halt] = O(1/ε)", part: "V" },
      { id: "A18", name: "Orthogonality",        body: "⟹⎕¹ ⟂ ⟹⎕² ⊩ opt(⟹⎕¹ ⊗ ⟹⎕²) = opt(⟹⎕¹) ⊗ opt(⟹⎕²)", part: "V" },
      { id: "A19", name: "Reliability",          body: "Σᵤ wᵤ = 1 ∧ ∀u : wᵤ ≥ 0", part: "V" },
      { id: "A20", name: "Meta-navigation",      body: "System-2 = ⟹ᵐⁿᵃᵛ¹(System-1)", part: "V" },
      { id: "A21", name: "Anti-foundation",      body: "relationships >ʳᵉˡ entities; no entity has isolated existence", part: "V" },
      { id: "A22", name: "Epistemic humility",   body: "confidence < θ ⊩ ∃ acquisition_plan : P(confidence↑ | plan) > 0", part: "V" },
      { id: "A23", name: "Effective capability", body: "effective ⟺ completion ∧ grounding ∧ coupling", part: "VIII" },
      { id: "A24", name: "Central diagnostic",   body: "viable (𝒜₇) ⟺ governing {△} grounded in perceptual (○) — else hollow 𝒜₆", part: "VIII" },
      { id: "L1",  name: "Verification pipeline", body: "bottleneck = max(V_compute, V_judgment); lim_(AI→∞) V = V_judgment", part: "VI" },
      { id: "L2",  name: "Intentionality–gaming", body: "gaming-resistance ∝ I(x); gaming-space ⊆ null(representation)", part: "VI" },
      { id: "L3",  name: "Trust gap",            body: "opportunity ∝ (T_potential − T_kinetic) × duration", part: "VI" },
      { id: "L4",  name: "Promise-binding",      body: "α = |b_A ∩ b_P| / |b_P| ; α_chain ≤ min_i α_i", part: "VI" },
      { id: "L5",  name: "Temporal arbitrage",   body: "P(pass | t_low) > P(pass | t_high)", part: "VI" },
      { id: "L6",  name: "Verification relativity", body: "no objective V(x); only agent-relative V_A(x)", part: "VI" },
      { id: "L7",  name: "Architecture matching", body: "optimal agent scale matches task J* (cognitive / hybrid / statistical)", part: "VI" },
      { id: "ML",  name: "Meta-Law",             body: "alignment ∝ experiential_return — a system stays aligned only as long as action reshapes the actor", part: "VII" },
    ],

    categories: [
      { glyph: "(○)",  name: "Firstness — Quality",    body: "Monadic; pre-linguistic felt wholeness. Faces forward: felt incompleteness generates the attentional attractor. What-might-be.", ref: "§1" },
      { glyph: "[□]",  name: "Secondness — Encounter", body: "Dyadic; brute resistance, facticity, the past-saturated present. Faces what is actually here. What-is.", ref: "§1" },
      { glyph: "{△}",  name: "Thirdness — Abstraction",body: "Triadic; naming, convention, law, mediation. Derivative and retrospective: by the time a name arrives, the encounter is receding. What-tends-to-be.", ref: "§1" },
      { glyph: "((○)[□])", name: "Fast Empathy",  body: "Possibility meets resistance — immediate quality of otherness / conflict.", ref: "§6.1" },
      { glyph: "([□]{△})", name: "Fast Fluency",  body: "Actuality seeks pattern — skilled automatic performance.", ref: "§6.1" },
      { glyph: "({△}(○))", name: "Slow Empathy",  body: "Law meets novelty — reflective understanding of possibility.", ref: "§6.1" },
      { glyph: "((○){△})", name: "Slow Fluency",  body: "Possibility constrained by law — aesthetic quality of pattern and law.", ref: "§6.1" },
      { glyph: ".ii .ie .ci .ce", name: "Modal aspects", body: "instance/community × internal/external: (○).ii personal felt quality; {△}.ce formal rule.", ref: "§0.5" },
    ],

    gateMatrix: {
      rows: ["(○)-recruited", "{△}-initiated"],
      cols: ["[□]-grounded", "{△}-terminated"],
      cells: [
        [ { name: "Generative act",        verdict: "living"    },
          { name: "Inspired delusion",     verdict: "delusion"  } ],
        [ { name: "Competent execution",   verdict: "competent" },
          { name: "Administrative process",verdict: "dead"      } ],
      ],
      note: "The gate evaluates trajectory, not content (§7.1). §7.2 names the off-diagonal pathologies: “beautiful delusion” (R without G) and “competent-dead” (G without R).",
    },

    pathologyLayers: [
      { id: "structural",  name: "Structural",    question: "Is there a generative loop at all?" },
      { id: "attentional", name: "Attentional",   question: "Is genuine attention present in the loop?" },
      { id: "content",     name: "Content-phase", question: "Is the loop fed by [□]-encounter or {△}-abstraction?" },
      { id: "scalar",      name: "Scalar",        question: "Is the gate evaluated at the boundary's temporal resolution?" },
      { id: "temporal",    name: "Temporal",      question: "Is (○) forward, [□] present, {△} backward — or displaced?" },
    ],

    temporalPathologies: [
      { name: "Nostalgia",         body: "[□] locked on past states rather than the present-saturated-with-past." },
      { name: "Projection",        body: "R replaced by {△}-anticipation — the pull is reasoned, not felt." },
      { name: "Premature Closure", body: "{△} freezes a partial contact — the name closes rather than opens further encounter." },
    ],

    deathModes: [
      { id: "fossil",     name: "Fossil",     question: "Was this once alive?",       body: "Once living; the whole evolved past it. Trace of generative origin persists." },
      { id: "residue",    name: "Residue",    question: "Is this incomplete?",        body: "The loop was operating but attention withdrew before completion." },
      { id: "imposition", name: "Imposition", question: "Was this ever recruited?",   body: "Never alive; imposed by {△} without recruitment or encounter. Most resistant: removal leaves a void with no latent structure." },
    ],

    trichotomies: [
      { n: 1,  aspect: "Material Form",            glyph: "⦿",    first: "Qualisign ⦿○",    second: "Sinsign ⦿□",     third: "Legisign ⦿△" },
      { n: 2,  aspect: "Immediate Object",         glyph: "⊕",    first: "Descriptive ⊕○",  second: "Designative ⊕□", third: "Copulant ⊕△" },
      { n: 3,  aspect: "Dynamic Object",           glyph: "⊗",    first: "Abstractive ⊗○",  second: "Concretive ⊗□",  third: "Collective ⊗△" },
      { n: 4,  aspect: "Sign–Object Relation",     glyph: "≈ ⇢ ≡", first: "Icon ≈",         second: "Index ⇢",        third: "Symbol ≡" },
      { n: 5,  aspect: "Immediate Interpretant",   glyph: "⚡",    first: "Ejaculative ⚡○", second: "Imperative ⚡□",  third: "Significative ⚡△" },
      { n: 6,  aspect: "Dynamic Interpretant",     glyph: "⚯",    first: "Sympathetic ⚯○",  second: "Shocking ⚯□",    third: "Usual ⚯△" },
      { n: 7,  aspect: "Sign–Interpretant Relation", glyph: "⋙",  first: "Suggestive ⋙○",   second: "Imperative ⋙□",  third: "Indicative ⋙△" },
      { n: 8,  aspect: "Final Interpretant",       glyph: "⧖",    first: "Gratific ⧖○",     second: "Action ⧖□",      third: "Self-Control ⧖△" },
      { n: 9,  aspect: "Sign–Final Relation",      glyph: "⊣",    first: "Rheme ⊣○",        second: "Dicisign ⊣□",    third: "Argument ⊣△" },
      { n: 10, aspect: "Triadic Assurance",        glyph: "⍚",    first: "Instinct ⍚○",     second: "Experience ⍚□",  third: "Form ⍚△" },
    ],

    signClasses: [
      { cls: "⟨⦿○ ≈ ⊣○⟩", name: "Qualisign–Icon–Rheme",       body: "Pure quality; System-1 felt similarity." },
      { cls: "⟨⦿□ ⇢ ⊣□⟩", name: "Sinsign–Index–Dicisign",     body: "Evidence; concrete efficacy; grounding." },
      { cls: "⟨⦿△ ≡ ⊣△⟩", name: "Legisign–Symbol–Argument",   body: "Law-governed inference; System-2 rule." },
      { cls: "⟨⦿△ ≡ ⊣α⟩", name: "Legisign–Symbol–Abduction",  body: "Hypothesis generation under law." },
      { cls: "⟨⦿△ ⥹ ⊣ι⟩", name: "Legisign–Metonymy–Induction", body: "Evidence integration by contiguity." },
    ],

    dimensions: [
      { n: 1,  name: "Distinction-Making Autonomy", cls: "⟨⦿△≡⊣α⟩", family: "Core" },
      { n: 2,  name: "Choice Architecture",         cls: "⟨⦿△⥹⊣ι⟩", family: "Core" },
      { n: 3,  name: "Efficacy of Action",          cls: "⟨⦿□⇢⊣□⟩", family: "Core" },
      { n: 4,  name: "Action Integration",          cls: "⟨⦿△⍥⊣α⟩", family: "Core" },
      { n: 5,  name: "Sphere of Influence",         cls: "⟨⦿□⥹⊣ι⟩", family: "Spatiotemporal" },
      { n: 6,  name: "Temporal Reach",              cls: "⟨⦿△⥹⊣□⟩", family: "Spatiotemporal" },
      { n: 7,  name: "Action Tempo",                cls: "⟨⦿⋮⇢⊣□⟩", family: "Spatiotemporal" },
      { n: 8,  name: "Self-Determination Depth",    cls: "⟨⦿△≡⊣△⟩", family: "Self-Authorship" },
      { n: 9,  name: "Boundary Negotiation",        cls: "⟨⦿⨀⍥⊣α⟩", family: "Self-Authorship" },
      { n: 10, name: "Regenerative Capacity",       cls: "⟨⦿⋮⇢⊣ι⟩", family: "Self-Authorship" },
      { n: 11, name: "Environmental Engagement",    cls: "⟨⦿△⥹⊣ι⟩", family: "Relational" },
      { n: 12, name: "Collective Capacity",         cls: "⟨⦿△≡⊣□⟩", family: "Relational" },
      { n: 13, name: "Communicative Power",         cls: "⟨⦿△≡⊣□⟩", family: "Relational" },
      { n: 14, name: "Path Authorship",             cls: "⟨⦿△⍥⊣α⟩", family: "Developmental" },
      { n: 15, name: "Growth Orchestration",        cls: "⟨⦿△⥹⊣ι⟩", family: "Developmental" },
      { n: 16, name: "Innovation Capacity",         cls: "⟨⦿△⍥⊣α⟩", family: "Developmental" },
      { n: 17, name: "Value Authorship",            cls: "⟨⦿△≡⊣△⟩", family: "Motivational" },
      { n: 18, name: "Evaluative Sovereignty",      cls: "⟨⦿△≡⊣△⟩", family: "Motivational" },
      { n: 19, name: "Purpose Emergence",           cls: "⟨⦿△⥹⊣α⟩", family: "Motivational" },
      { n: 20, name: "Subjective Presence",         cls: "⟨⦿○⌘⊣○⟩", family: "Experiential" },
      { n: 21, name: "Emotional Range",             cls: "⟨⦿⟡⍥⊣○⟩", family: "Experiential" },
      { n: 22, name: "Agency Awareness",            cls: "⟨⦿△⍥⊣α⟩", family: "Experiential" },
      { n: 23, name: "Embodiment Form",             cls: "⟨⦿□⇢⊣□⟩", family: "Resource" },
      { n: 24, name: "Resource Mobilization",       cls: "⟨⦿□⥹⊣□⟩", family: "Resource" },
      { n: 25, name: "Contextual Position",         cls: "⟨⦿△⥹⊣□⟩", family: "Resource" },
    ],

    loops: [
      { glyph: "⦿O", name: "Operational",  body: "C₂ Action chain; contained by management: ⦿M ⊃ ⦿O." },
      { glyph: "⦿P", name: "Policy",       body: "C₃ Governance chain." },
      { glyph: "⦿M", name: "Management",   body: "Contains operations without commanding them." },
      { glyph: "⦿I", name: "Intelligence", body: "Empirical coupling: ⦿O ⟿ₑ ⦿I — operational outputs feed intelligence." },
      { glyph: "⦿G", name: "Governance",   body: "Grounded-knowledge dialectic: ⦿K ⋈ ⦿G." },
      { glyph: "⦿L", name: "Legitimation", body: "C₃ Governance chain." },
      { glyph: "⦿C", name: "Coupling",     body: "Λ coupling spine between chains." },
      { glyph: "⦿K", name: "Knowledge",    body: "Grounded-knowledge dialectic with ⦿G." },
      { glyph: "H(⦿M,⦿I;⦿P)", name: "Central homeostat", body: "Held in productive tension Hₕ; its collapse is Hₓ." },
    ],

    failureForces: [
      { glyph: "PMG",   name: "Purpose–Metric Gap",      body: "1 − correlation(metric, purpose_outcomes): the space optimization pressure leaks into." },
      { glyph: "OP",    name: "Optimization Pressure",   body: "Environmental/competitive force toward the target regardless of side effects." },
      { glyph: "∇H",    name: "Hacking gradient",        body: "Directional pressure to exploit PMG; grows with gap × pressure." },
      { glyph: "⤋",     name: "Alignment decay",         body: "Alignment degrades over time without active maintenance." },
      { glyph: "⟨⟨⟩⟩",  name: "Meta-hacking recursion",  body: "Each anti-hacking measure becomes a new optimization target." },
      { glyph: "⤓ₑ",    name: "Experiential attenuation",body: "Felt connection between action and consequence weakens with scale, abstraction, delegation depth, proxy layers." },
    ],

    // the board's own rules of play — what moves mean and what they do
    semantics: [
      { group: "Moving between columns — constraints (checked before every move)", rows: [
        { left: "A13 · horizon = 1",     body: "Forward moves are limited to the adjacent column — the option space past the next gate passage does not yet exist. Backward jumps are free (return is always sanctioned)." },
        { left: "A9 · dual gate",        body: "Gate → Articulation only for living trajectories: (○)-recruited, [□]-grounded, and S ≥ θ simultaneously. {△}-articulation before dual passage is dead naming." },
        { left: "§14 · diagnose first",  body: "A card that fails the gate cannot return toward Initiation until a layer is located on the five-layer model (§13). The blocked move completes itself once diagnosed." },
        { left: "A7 · genesis",          body: "Entering Synthesize requires a declared emergent property — one present in neither parent constructor." },
      ]},
      { group: "Moving between columns — actions (fired by a successful move)", rows: [
        { left: "trace (§9.2)",          body: "Every transition is appended to the card's own trace — the post-hoc articulation of a process navigated one gate-passage at a time. Visible in the card's detail view." },
        { left: "gate entry (§8)",       body: "Arriving in Gate Evaluation records the verdict with its numbers: S = ρ − δ − γ·ln k against θ." },
        { left: "dual passage (A9)",     body: "Gate → Articulation logs the passage — naming proceeds strictly downstream of it." },
        { left: "χ schedule (§19)",      body: "Advancing a dialectic phase moves contentiousness along the schedule: 0.9 →|π 0.7 →|π 0.5 →|π 0.3." },
        { left: "Γ update (§19)",        body: "A position surviving a phase transition gains reliability by EMA: Γ ← 0.7·Γ + 0.3 — and every weight w = (Γ+ε₀)/Σ(Γ+ε₀) on the board recomputes." },
        { left: "↻ cycle (A12)",         body: "Returning from Recursive Closure to Initiation increments the cycle counter: state, R-topology, and boundaries have shifted." },
      ]},
      { group: "Promotion between boards — the meta-workflow", rows: [
        { left: "Closure → Explore",     body: "A resolved structure whose question is now contested becomes a dialectic position (⟨⦿△ ≡ ⊣α⟩, Γ = 0.70, next agent handle). §15: System-2 = coordinated(System-1)." },
        { left: "Synthesize → Initiation", body: "An emergent constructor becomes a transformation with fresh gate metrics — genesis is not automatically living; it must pass 𝒢 (§7.4)." },
        { left: "death mode → Phase 0",  body: "A card diagnosed fossil / residue / imposition escalates to the Resolution Procedure as an intervention; the diagnosis carries over as tags (§11, §29)." },
        { left: "Phase 5 → Initiation",  body: "Evolutionary iteration returns the redesigned structure to living process (§29)." },
      ]},
      { group: "What promotion transforms", rows: [
        { left: "fields",                body: "Gate fields (trajectory, ρ δ γ k θ, scale) strip when leaving the protocol and appear with defaults when entering it; the sign class is re-issued for the target board; context axioms are added." },
        { left: "lineage",               body: "The card keeps title, notes, and trace; an origin chip records where it was promoted from, and the trace entry carries the governing section." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- learn */

  learn: {

    tour: [
      { sel: ".brand", title: "Directed autopoietic navigation",
        body: "QPT models every process through three categories: (○) Firstness — felt quality, [□] Secondness — causal encounter, {△} Thirdness — law and naming (§1). This workbench makes you work them, not just read them." },
      { sel: "#board-tabs", title: "Three workflows",
        body: "Each board is a workflow from the specification: the Generative Protocol (§14), the Scheduled Dialectic (§19), and the Resolution Procedure (§29)." },
      { sel: 'section.column[data-column="initiation"]', board: "protocol", title: "Columns are protocol steps",
        body: "The protocol runs (○) Initiation → [□] Encounter → 𝒢 Gate → {△} Articulation → ↻ Closure. Commitment horizon = 1 (A13): cards advance one column at a time — drag one two columns over and read the refusal." },
      { sel: '.card[data-id="p1"]', board: "protocol", title: "Anatomy of a card",
        body: "Every card is a transformation: a sign class, a trajectory (source → target), and anchoring metrics. S = ρ − δ − γ·ln k is tested against θ (§8). Click any card to open its gate evaluation and editor — every passage is logged there as the card's own post-hoc trace (§9.2)." },
      { sel: 'section.column[data-column="gate"]', board: "protocol", title: "The Quality Gate",
        body: "𝒢 ≡ R ⊓ G (§7). Only living trajectories — (○)-recruited, [□]-grounded, S ≥ θ — advance to articulation (A9). Failures must be diagnosed on the five-layer model (§13) before they may return." },
      { sel: 'section.column[data-column="closure"]', board: "protocol", title: "Recursive closure",
        body: "After passage, the enlarged whole is re-sensed: state, R-topology, and boundaries have shifted (A12). Cards here can ↻ return to Initiation — the graph produces itself through its own operation." },
      { sel: "#board form.new-card", board: "protocol", title: "Creating cards",
        body: "Every board admits new cards at its entry-point column: transformations at Initiation, positions and moderator notes at Explore, interventions at Phase 0. Nothing enters mid-workflow — everything walks from the start (A13)." },
      { sel: "#board-tabs", title: "Promotion between boards",
        body: "The boards are one meta-workflow. From a card's detail view: Recursive Closure promotes a card into the dialectic as a position (§15); a synthesis returns to the protocol to be grounded (§7.4); diagnosed dead structure escalates to the Resolution Procedure (§11); Phase 5 returns to living process (§29)." },
      { sel: "#ref-btn", title: "Reference & drill",
        body: "The full registry — the Semantics tab (the rules every move and promotion obeys), formulas, axioms A1–A24, laws L1–L7, the Meta-Law, trichotomies, dimensions — plus a Drill tab for flashcard practice. Rejection toasts link straight into the registry." },
      { sel: "#practice-btn", title: "Practice",
        body: "Guided exercises run on the live board, and the specification's own constraints are the grader. Start with “Return to step 1”." },
    ],

    exercises: [
      { id: "e1", board: "protocol", title: "Return to step 1", refs: ["§14", "A9", "§13"],
        goal: "A felt wrongness fails the gate as a beautiful delusion — R without G. Diagnose its pathology layer, then return the card to Initiation.",
        hint: "Try dragging it back to Initiation. The protocol requires a five-layer diagnosis before any return (§14, step 3).",
        setup: { id: "tut1", column: "gate",
          title: "Felt wrongness in the query planner", sign: "⟨⦿○ ≈ ⊣○⟩", signName: "Qualisign–Icon–Rheme",
          source: "recruited", target: "terminated",
          rho: 0.88, delta: 0.35, gamma: 0.25, k: 5, theta: 0.50,
          scale: "micro", cycle: 0, pathology: null, death: null, axioms: ["A9", "A10"],
          note: "Strong pull, no causal landing yet. What does it need before naming?" },
        done: (c) => c.column === "initiation" && !!c.pathology,
        explain: "The gate failed, so the protocol routed through the five-layer diagnostic before the return to step 1. Proceed only on dual passage (A9)." },

      { id: "e2", board: "protocol", title: "Tune the support, not the story", refs: ["§8", "A9"],
        goal: "This transformation is (○)-recruited and [□]-grounded, but S < θ — stuck at the phase transition. Tune its anchoring metrics until the gate passes it, then advance it to Articulation.",
        hint: "Raise ρ (support) or lower δ (mismatch) — and ask whether θ fits the task. The gate admits only S ≥ θ.",
        setup: { id: "tut2", column: "gate",
          title: "Anchor the caching decision in real traces", sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          source: "recruited", target: "grounded",
          rho: 0.70, delta: 0.25, gamma: 0.25, k: 4, theta: 0.50,
          scale: "meso", cycle: 0, pathology: null, death: null, axioms: ["A9", "A15"],
          note: "The encounter happened; the consensus is still too thin to anchor." },
        done: (c) => c.column === "articulation" && (c.rho - c.delta - c.gamma * Math.log(c.k)) >= c.theta,
        explain: "S ≥ θ with both conjuncts holding: the phase transition is crossed (A15). Quantitatively, ρ carried R and low δ carried G." },

      { id: "e3", board: "protocol", title: "One gate at a time", refs: ["A13", "A12"],
        goal: "Bring this living transformation from Initiation to Recursive Closure. The board will refuse every shortcut.",
        hint: "The refusal is the lesson: the option space after the next gate passage does not yet exist (A13).",
        setup: { id: "tut3", column: "initiation",
          title: "The onboarding drop-off, re-recruited", sign: "⟨⦿□ ⇢ ⊣□⟩", signName: "Sinsign–Index–Dicisign",
          source: "recruited", target: "grounded",
          rho: 0.90, delta: 0.10, gamma: 0.20, k: 2, theta: 0.40,
          scale: "meso", cycle: 0, pathology: null, death: null, axioms: ["A12", "A13"],
          note: "Living and ready — but even living cards walk one column at a time." },
        done: (c) => c.column === "closure",
        explain: "Five passages, no skips. A generative sequence is a post-hoc trace of a process navigated one gate-passage at a time (§9.2)." },

      { id: "e4", board: "protocol", title: "Make the name live", refs: ["§12", "A14"],
        goal: "“Q3 dashboard” is jargon: its trajectory is {△} → {△}. Without renaming it, make the name live.",
        hint: "Open the card and re-aim its trajectory on the gate matrix. A name lives by (○) → [□], not by wording (§12).",
        setup: { id: "tut4", column: "articulation",
          title: "Q3 dashboard", sign: "⟨⦿△ ≡ ⊣△⟩", signName: "Legisign–Symbol–Argument",
          source: "initiated", target: "terminated",
          rho: 0.55, delta: 0.20, gamma: 0.25, k: 3, theta: 0.40,
          scale: "meso", cycle: 0, pathology: null, death: null, axioms: ["A10", "A14"],
          note: "Signals membership, enables no contact. The string is not the problem — the trajectory is." },
        done: (c) => c.source === "recruited" && c.target === "grounded",
        explain: "Same words, new trajectory: recruited at (○), grounded at [□] — a living name that opens new diagnostics (§12)." },

      { id: "e5", board: "dialectic", title: "Birth a constructor", refs: ["A7", "§6.2"],
        goal: "This position has survived integration and consolidation. Carry it through genesis into Synthesize.",
        hint: "Move it into Synthesize and A7 will tell you what is missing: an emergent property present in no parent.",
        setup: { id: "tut5", column: "consolidate", kind: "position", agent: "u₉",
          title: "Tiered TTL with hand-tuned constants", sign: "⟨⦿△ ≡ ⊣α⟩", signName: "Legisign–Symbol–Abduction",
          reliability: 0.70, cycle: 0, genesis: null, axioms: ["A7"],
          note: "Consolidated — but consolidation is not genesis. What property does the synthesis have that neither parent had?" },
        done: (c) => c.column === "synthesize",
        explain: "∃ property([□]⎕ₑw) ∉ parents — emergence, not compromise (A7). The dialectic produced something new." },
    ],
    /* narrated end-to-end scenario — one card through every stage.
       Each step: optional board switch, optional spotlight selector, narration text,
       and a run(api) that drives the real board code (moves, edits, promotions). */
    simulation: [
      { board: "protocol", sel: "#board form.new-card",
        text: "(○) Initiation — a practitioner feels something off in the onboarding flow. Attention is captured, not scanned (A11): we record the locus and enter a transformation. The hunch is genuine but ungrounded — its target is {△}-terminated.",
        run: (api) => api.createSimCard() },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "[□] Encounter — we sit with actual session recordings of the drop-off point. Contact first, metrics later. The card advances exactly one column: commitment horizon = 1 (A13).",
        run: (api) => api.move("sim1", "encounter") },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "𝒢 Gate Evaluation — the gate scores the trajectory, not the content: (○)-recruited but {△}-terminated, and S = 0.20 < θ 0.50. Verdict: Beautiful delusion — R without G. The trace records the evaluation (§9.2).",
        run: (api) => api.move("sim1", "gate") },
      { board: "protocol", sel: null,
        text: "Try to name it anyway — drag toward Articulation. A9 refuses: {△}-articulation before dual passage is dead naming. This refusal is the specification running, not a UI quirk.",
        run: (api) => api.move("sim1", "articulation") },
      { board: "protocol", sel: null,
        text: "Retreat without a diagnosis? §14 refuses as well: a failed gate must be located on the five-layer model before any return to step 1.",
        run: (api) => { api.close(); api.move("sim1", "initiation"); } },
      { board: "protocol", sel: null,
        text: "We diagnose: Attentional — the pull was genuine, but no one stayed with the encounter. The moment the layer is set, the blocked return completes itself: back to Initiation.",
        run: (api) => api.edit("sim1", (c) => { c.pathology = "attentional"; }) },
      { board: "protocol", sel: null,
        text: "Second encounter — this time with instruments: traces, support tickets, funnel logs. The encounter changes the numbers and the landing: ρ 0.85 → 0.93, δ 0.30 → 0.08, and the target is now [□]-grounded.",
        run: (api) => { api.move("sim1", "encounter"); api.open("sim1"); api.edit("sim1", (c) => { c.rho = 0.93; c.delta = 0.08; c.target = "grounded"; }); } },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "Back at the gate: S = 0.93 − 0.08 − 0.25·ln 4 ≈ 0.503 ≥ θ 0.50, with R ∧ G — Living, right at the phase transition (Zone 2), P(anchored) ≈ 51%.",
        run: (api) => { api.close(); api.move("sim1", "gate"); } },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "Dual passage (A9) — naming is licensed, strictly downstream of passage. The name arrives through contact: “The unowned hour after signup”. A living name (§12).",
        run: (api) => { api.move("sim1", "articulation"); api.edit("sim1", (c) => { c.title = "The unowned hour after signup"; }); } },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "↻ Recursive Closure — the enlarged whole is re-sensed: the weakest point has moved, new adjacencies exist (A12). We could ↻ return for another cycle — but this question is about to be contested by the whole team.",
        run: (api) => api.move("sim1", "closure") },
      { board: "dialectic", sel: '.card[data-id="sim1"]',
        text: "Promotion (§15): System-2 = coordinated(System-1). The card becomes a position in Explore — a fresh agent handle, Γ = 0.70, its weight w computed across the board.",
        run: (api) => api.promoteTo("sim1", "dialectic") },
      { board: "dialectic", sel: '.card[data-id="sim1"]',
        text: "Integrate — evidence arrives. χ follows the schedule 0.9 → 0.7, and surviving the phase raises reliability by EMA: Γ 0.70 → 0.79; its weight grows (§19).",
        run: (api) => api.move("sim1", "integrate") },
      { board: "dialectic", sel: '.card[data-id="sim1"]',
        text: "Consolidate — rules form. χ 0.7 → 0.5; Γ 0.79 → 0.85. The moderator watches Σᶜᵒⁿᵛ for the plateau that licenses synthesis.",
        run: (api) => api.move("sim1", "consolidate") },
      { board: "dialectic", sel: null,
        text: "Into Synthesize? A7 refuses: genesis requires an emergent property present in neither parent — compromise is not emergence.",
        run: (api) => api.move("sim1", "synthesize") },
      { board: "dialectic", sel: null,
        text: "We name what is genuinely new: signup-hour ownership — no parent had it. The pending move completes itself: ⋗ᵉ, an emergent constructor is born.",
        run: (api) => api.edit("sim1", (c) => { c.genesis = "signup-hour ownership"; }) },
      { board: "protocol", sel: '.card[data-id="sim1"]',
        text: "And the constructor returns to be grounded (§7.4): promoted back to Initiation, where it must pass the same gate as everything else. One full navigation — (○) → [□] → 𝒢 → {△} → ↻, coordination, genesis, and home.",
        run: (api) => api.promoteTo("sim1", "protocol") },
    ],
  },
};
